name: CI
on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.20'
            - name: Install artifacts
              run: |
                  go install -v github.com/golang/mock/mockgen@v1.6.0
                  go install github.com/mattn/goveralls@latest
            - name: Test
              env:
                TOKEN_SECRET_KEY: ${{ secrets.TEST_JWT_SECRET_KEY }}
                APP_HOST: localhost
              run: |
                  echo "machine github.com login ${{ secrets.GORGOM_ACCESS_TOKEN }}" > ~/.netrc
                  make test TEST_FLAGS="-v -race -covermode=atomic -coverprofile=cover.out"
            - name: Report coverage
              env:
                COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
              run: goveralls -coverprofile=cover.out -service=github
